version: "3.7"

services:
  greeting:
    restart: on-failure
    image: agarwalconsulting/spring-greeting

  curl-test:
    restart: always
    build:
      context: ./curl-test
    command: sleep 1000
