server:
  port: 9000
ribbon:
  eureka:
    enabled: false
zuul:
  debug:
    request: true
    include-debug-header: true
  routes:
    products:
      path: /products/**
      url: http://localhost:9001/products
    orders:
      path: /orders/**
      url: http://localhost:9002/orders